version: '3'

services:

  headlessbot:
    image: n0thub/headlessmc:1.8.1
    container_name: 'headlessbot'
    command: launch "fabric-loader-0.15.6-1.20.4"
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - '${PWD}/run/mc:/work/.minecraft'
      - '${PWD}/run/hmc:/work/HeadlessMC'

  grafana:
    image: grafana/grafana:latest
    container_name: 'grafana'
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - '${PWD}/grafana/provisioning:/etc/grafana/provisioning'
    env_file:
      - './grafana/config.env'

  prometheus:
    image: prom/prometheus:latest
    container_name: 'prometheus'
    ports:
      - '127.0.0.1:9090:9090'
    volumes:
      - '${PWD}/prometheus.yaml:/etc/prometheus/prometheus.yml:ro'
