version: '3'

services:

  grafana:
    image: grafana/grafana:latest
    container_name: 'grafana'
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - '${PWD}/grafana/provisioning:/etc/grafana/provisioning'
    env_file:
      - './grafana/config.env'

  prometheus:
    image: prom/prometheus:latest
    container_name: 'prometheus'
    ports:
      - '127.0.0.1:9090:9090'
    volumes:
      - '${PWD}/prometheus.yaml:/etc/prometheus/prometheus.yml:ro'
