org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

# mod properties
maven_group = lol.hub
mod_name = headlessbot
mod_version = 0.1.0-SNAPSHOT

# some version numbers
headlessmc_version=2.5.1
junit_version=5.11.3
prometheus_lib_version=1.3.6

# fabric stuff
# https://modmuss50.me/fabric.html
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
fabric_loader_version=0.16.13
fabric_api_version=0.120.0+1.21.5
