name: '🚔'
on: [ push ]
jobs:
  check:
    if: startsWith(github.ref, 'refs/tags/v') == false
    runs-on: ubuntu-22.04
    steps:

      - name: 'checkout'
        uses: actions/checkout@v4.0.0

      - name: 'validate gradle wrapper'
        uses: gradle/wrapper-validation-action@v1

      - name: 'setup java'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: 'run checks'
        run: |
          make check
