name: '🚔'
on: [ push ]
jobs:
  check:
    if: startsWith(github.ref, 'refs/tags/v') == false
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - run: |
          ./gradlew --console plain --info --full-stacktrace clean check
